<a href="https://colab.research.google.com/github/bv8904/Submarine-Obstacle-Detection/blob/main/submarine_obstacle_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing all the important and necessary Libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

#Uploading the dataset

In [3]:
dataset=pd.read_csv('/content/Synthetic_Sonar_Data.csv',header=None)
print(dataset.shape)
#head() prints the first five rows of dataset
print(dataset.head())
#describe() gives all the statistical values
dataset.describe()

(501, 61)
         0         1         2         3         4         5         6   \
0  0.020000  0.037100  0.042800  0.020700  0.095400  0.098600  0.153900
1  0.007767  0.066808  0.049812  0.026783  0.001377  0.049158  0.109198
2  0.065215  0.077874  0.132430  0.161748  0.126843  0.139350  0.122959
3  0.039488  0.020291  0.031210  0.053985  0.104470  0.151661  0.149020
4  0.070869  0.075712  0.208653  0.260999  0.319737  0.207413  0.071266

         7         8         9   ...        51        52        53        54  \
0  0.160100  0.310900  0.211100  ...  0.002700  0.006500  0.015900  0.007200
1  0.113169  0.153418  0.233588  ...  0.009846  0.011918  0.000264  0.018741
2  0.186082  0.198978  0.199775  ...  0.006424  0.017569  0.011769 -0.002835
3  0.120324  0.171208  0.194417  ... -0.006760 -0.016182  0.023021 -0.005277
4  0.219432  0.086908  0.089215  ...  0.027717  0.000604  0.035462  0.029134

         55        56        57        58        59  60
0  0.016700  0.018000  0.008400  0.009000  0.003200   R
1 -0.001031 -0.005312 -0.005539  0.005096 -0.001970   M
2  0.009973  0.006760  0.012405  0.029043  0.004210   M
3  0.012119  0.011186  0.001122 -0.003490  0.008238   M
4  0.014287  0.025193  0.017862  0.016722  0.008203   M

[5 rows x 61 columns]

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,...,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000
mean,0.029670,0.041664,0.047298,0.056745,0.078637,0.106408,0.124098,0.142186,0.184798,0.212807,...,0.015743,0.013361,0.010725,0.009903,0.008768,0.007718,0.008585,0.008098,0.008273,0.006707
std,0.026544,0.036467,0.045600,0.057714,0.064515,0.062005,0.060956,0.085426,0.119623,0.142873,...,0.016121,0.013017,0.012563,0.012615,0.011921,0.011992,0.011570,0.011565,0.012170,0.011076
min,-0.022535,-0.020086,-0.017715,-0.014442,-0.012839,-0.005445,-0.005466,-0.010533,-0.002797,0.003605,...,-0.016343,-0.017472,-0.021947,-0.024423,-0.020363,-0.031208,-0.025692,-0.029668,-0.030109,-0.028257
25%,0.013828,0.018436,0.019478,0.022980,0.034356,0.065840,0.081423,0.085478,0.098756,0.107709,...,0.004927,0.004100,0.002401,0.001871,0.001354,-0.000857,0.001489,0.000937,0.000097,-0.000765
50%,0.024516,0.034015,0.036305,0.044456,0.064605,0.092504,0.112517,0.117689,0.152812,0.185593,...,0.013867,0.012172,0.010212,0.009168,0.008601,0.008084,0.008139,0.008257,0.008051,0.005715
75%,0.038333,0.054054,0.058403,0.068716,0.104470,0.133533,0.163705,0.193249,0.259611,0.281971,...,0.025047,0.020801,0.017918,0.017554,0.015973,0.014577,0.015720,0.014692,0.016761,0.013650
max,0.153665,0.243733,0.327952,0.433043,0.406973,0.407858,0.386983,0.453212,0.676788,0.706637,...,0.096589,0.081936,0.052501,0.060911,0.050990,0.049436,0.048558,0.052253,0.046178,0.060193

#Checking for null values

In [4]:
#checking for null values
print(dataset.isnull().sum())
#checking for number of rocks and mines in dataset
print(dataset[60].value_counts())

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64
60
R    251
M    250
Name: count, dtype: int64

In [5]:
Y=dataset[60]
X=dataset.drop(columns=60,axis=1)
#data
print(X)
#labels
print(Y)

           0         1         2         3         4         5         6   \
0    0.020000  0.037100  0.042800  0.020700  0.095400  0.098600  0.153900
1    0.007767  0.066808  0.049812  0.026783  0.001377  0.049158  0.109198
2    0.065215  0.077874  0.132430  0.161748  0.126843  0.139350  0.122959
3    0.039488  0.020291  0.031210  0.053985  0.104470  0.151661  0.149020
4    0.070869  0.075712  0.208653  0.260999  0.319737  0.207413  0.071266
..        ...       ...       ...       ...       ...       ...       ...
496  0.003423  0.037159  0.006185  0.010215  0.027473  0.058742  0.101263
497  0.026831  0.018951  0.006991  0.014532  0.019128  0.028971  0.059366
498  0.027739  0.042234  0.015132  0.027327  0.047482  0.139746  0.213281
499  0.042652  0.048381  0.045229  0.058429  0.009955  0.080325  0.186948
500  0.011472  0.029085  0.065838  0.023066  0.028478  0.027347  0.111246

           7         8         9   ...        50        51        52  \
0    0.160100  0.310900  0.211100  ...  0.023200  0.002700  0.006500
1    0.113169  0.153418  0.233588  ...  0.022537  0.009846  0.011918
2    0.186082  0.198978  0.199775  ...  0.022868  0.006424  0.017569
3    0.120324  0.171208  0.194417  ...  0.030576 -0.006760 -0.016182
4    0.219432  0.086908  0.089215  ...  0.027834  0.027717  0.000604
..        ...       ...       ...  ...       ...       ...       ...
496  0.048416  0.128296  0.133505  ... -0.014050  0.015371  0.014846
497  0.046717  0.112690  0.107709  ...  0.013759  0.002357 -0.007936
498  0.117689  0.083030  0.171025  ...  0.005028  0.003714  0.007635
499  0.171890  0.171705  0.129375  ...  0.022748  0.012910  0.008486
500  0.130245  0.065665  0.129322  ...  0.028057  0.007375  0.010473

           53        54        55        56        57        58        59
0    0.015900  0.007200  0.016700  0.018000  0.008400  0.009000  0.003200
1    0.000264  0.018741 -0.001031 -0.005312 -0.005539  0.005096 -0.001970
2    0.011769 -0.002835  0.009973  0.006760  0.012405  0.029043  0.004210
3    0.023021 -0.005277  0.012119  0.011186  0.001122 -0.003490  0.008238
4    0.035462  0.029134  0.014287  0.025193  0.017862  0.016722  0.008203
..        ...       ...       ...       ...       ...       ...       ...
496  0.007471  0.002138  0.007945  0.001489 -0.001143  0.012255 -0.009311
497  0.008689  0.015097  0.008526  0.014984 -0.003945  0.008646  0.016139
498  0.016677  0.013711  0.033042  0.003260  0.013266  0.001887  0.030363
499 -0.001866  0.014986  0.025054 -0.008346  0.003677  0.016752  0.004245
500  0.013327  0.014170  0.005088  0.007519  0.011605  0.008526  0.016474

[501 rows x 60 columns]
0      R
1      M
2      M
3      M
4      M
      ..
496    R
497    R
498    R
499    R
500    R
Name: 60, Length: 501, dtype: object

#Training and Testing the data

In [6]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,stratify=Y,random_state=2)
print(X.shape)
print(X_train.shape)
print(X_test.shape)
print(Y.shape)
print(Y_train.value_counts())
print(Y_test.value_counts())

(501, 60)
(450, 60)
(51, 60)
(501,)
60
M    225
R    225
Name: count, dtype: int64
60
R    26
M    25
Name: count, dtype: int64

#Logistic Regression

In [7]:
lrmodel = LogisticRegression(class_weight='balanced',max_iter=100)
#Trainig the model
lrmodel.fit(X_train, Y_train)
#predicting labels for the training data
train_prediction=lrmodel.predict(X_train)
#evaluating the accuracy of the model for training data
train_accuracy=accuracy_score(train_prediction,Y_train)
#printing training accuracy
print(train_accuracy)
#predicting labels for the testing data
test_prediction=lrmodel.predict(X_test)
#evaluating the accuracy of the model for testing data
test_accuracy=accuracy_score(test_prediction,Y_test)
#printing testing accuracy
print(test_accuracy)

0.8644444444444445
0.8235294117647058

#Checking the model

In [8]:
input=np.array([0.036585799186803866,0.08839022399805957,0.19781571683253513,0.2851220070874348,0.3122836608750912,0.20992585215574158,0.04250676317389193,0.23372054266103756,0.09412264027354961,0.08256233481803275,0.15842765882085705,0.2270470660605624,0.2855369813932157,0.33894165853374497,0.44817132721226877,0.40007739315219987,0.5664109579640306,0.69224499410348,0.851850581924657,0.9244796203745261,0.9216811569000803,0.9978134065250895,0.9575082838574089,0.9134082690191987,0.8349157817100175,0.703334000480721,0.6464367486283945,0.447630893899002,0.25359656658142604,0.2010726258700606,0.1356336452083794,0.1084649307540981,0.1517329292796685,0.2466039805888602,0.43969443888366416,0.5125211296609352,0.442155462848276,0.4527364387100898,0.3973998817963874,0.27439261402258647,0.3356784324994813,0.5006649917200388,0.3392512931471823,0.14066341875239635,0.19017596105678886,0.14740498166083285,0.060620361975973154,0.06226459977158308,0.05193959708081245,0.004826057814596603,0.02306666755598804,0.024826129279857702,-0.003779342322630278,0.027161242350664812,0.006160399830899792,0.014911507672676762,0.0009772105979697493,0.02212003548571581,0.003947233467689212,0.008980706508582167])
input_reshape=input.reshape(1,-1)
input_prediction=lrmodel.predict(input_reshape)
if(input_prediction[0]=='R'):
  print('The object is a Rock')
else:
  print('The object is a Mine')

The object is a Mine